apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aes-vllm-cache
  labels:
    app.kubernetes.io/name: aes-vllm
    app.kubernetes.io/part-of: aes
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
