apiVersion: v1
kind: Service
metadata:
  name: aes-vllm
  labels:
    app.kubernetes.io/name: aes-vllm
    app.kubernetes.io/part-of: aes
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aes-vllm
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
